# Generated by Django 5.1.2 on 2025-01-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_username_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
